### ISSUE TITLE
LocalCatalog throws ValueError when you try to load a dataset

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-catalog-py#21]
I am trying to run the `LocalCatalog` as:

```python
from owid.catalog import LocalCatalog
cat = LocalCatalog(path=".../etl/data/")
```

But then when running `cat.find(namespace="faostat")` it raises an error.

Am I setting `LocalCatalog` to the wrong path? I am using the path to the data folder created after [running the etl](https://github.com/owid/etl) for some datasets.

Thanks!

**Comment by larsyencken** [comment]
Ah, there is a bug in the local catalog that doesn't allow you to call `.load()` on it. For now, you have to use a workaround and just construct `Dataset('path/to/dataset')` with the folder of the dataset you want.

---

From the ETL root folder, I tried this now:

```python
from owid.catalog import LocalCatalog
cat = LocalCatalog('data')
cat.find(namespace='faostat')   # ok, returns the matches
cat.find(namespace='faostat').iloc[0].load()  # fail with exception
```

The exception I got was:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-446dd2dd0bb9> in <module>
----> 1 cat.find(namespace='faostat').iloc[0].load()

~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/owid/catalog/catalogs.py in load(self)
    208                 raise ValueError("unknown format")
    209
--> 210         raise ValueError("series is not a table spec")
    211
    212

ValueError: series is not a table spec
```

**Comment by larsyencken** [comment]
It turned out that the reason that `.find()` worked for me was that I'd already reindexed my local catalog with `.venv/bin/reindex`. The PR above will do the reindex automatically if it's missing.
