### ISSUE TITLE
Creating a Table from an existing pandas dataframe does not create Variables for series

### ISSUE THREAD

**Issue by danyx23** [owid/owid-catalog-py#4]
When doing this:
```python
table = Table(df) # assume df has columns name and value

# then this doesn't work:
table.name.metadata.title = "Test"
```

**Comment by larsyencken** [comment]
We paired on this and decided to drop support for `table.name` mapping to `table.metadata.name`, since there is a conflict between this and Pandas mapping `table.name` to `table[name]`.

So now, we always write: `table.metadata.name = 'Test'` to avoid confusion
